### ISSUE TITLE
Inconsistent details in the README

### ISSUE THREAD

**Issue by seralouk** [ZigaSajovic/Consensus_Clustering#1]
Hi,

In the README, it is written: 

> NOTE: needs fit_predict method called with parameter n_clusters

However, scipy k-means do not have fit_predict method (https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html)

Did you mean scikit-learn models maybe?

**Comment by ZigaSajovic** [comment]
@seralouk Thank you for reporting this inconsistency. You are correct. I have fixed the README to reflect this.

**Comment by seralouk** [comment]
Thanks for correcting the README. Another suggestion would be to put a small toy example in the README. 
The following seems to not be working properly:
```
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
model = KMeans()

cc = ConsensusCluster(cluster=model, L=2, K=4,H=100)
cc.fit(X)
```
Throws:

> TypeError: 'KMeans' object is not callable

The solution is to call:
```
model = KMeans
```

**Comment by ZigaSajovic** [comment]
@seralouk As you have correctly concluded, model is supposed to be a `class`, and not an `object` (instance of a class).
I added further clarification in the README and the docs.

    Args:
      * cluster -> clustering class
        * NOTE: the class is to be instantiated with parameter `n_clusters`,
          and posses a `fit_predict` method, which is invoked on data.


Your suggestion for a toy example seems  appropriate. I will add it.
