### ISSUE TITLE
Resulting matrix has very large value?

### ISSUE THREAD

**Issue by ky-zhou** [ZigaSajovic/Consensus_Clustering#3]
I am using `kmeans` for the `ConsensusCluster` class (or others work same). Then `fit` and `predict` right after the first operation. The resulting matrix has 1s on the diagonal, but there are very large values like 500000.0 on some places in the matrix.
Is that a bug? Thanks. 

Here is full code:
```
        c = ConsensusCluster(cluster.KMeans, 2, 3, 4, 1)
        c.fit(self.d1)
        _, similarity1 = c.predict()
```
BTW I modified the source code so that the matrix with best k is also returned by `predict`. This `similarity1` has the issue.

**Comment by hlzl** [comment]
I would be interested in this as well. This also appears when using `AgglomerativeClustering`.

**Comment by hlzl** [comment]
I had a similar problem when using `AgglomerativeClustering`.

I was able to solve it by increasing the number of resamplings `H`. For me, `H=50` gave good results.

**Comment by ZigaSajovic** [comment]
This issue is resolved by @hlzl pull request.
